--- #YAML:1.0
name:                WWW-Sitebase
version:             0.9
abstract:            Base class for Perl modules
license:             ~
author:              
    - Grant Grueninger <grantg@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Config::General:               0
    File::Spec::Functions:         0
    IO::Prompt:                    0
    List::Compare:                 0
    Params::Validate:              0
    Spiffy:                        0.24
    Test::More:                    0
    WWW::Mechanize:                1.2
    YAML:                          0.39
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
