# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Sitebase
version:      0.5
version_from: lib/WWW/Sitebase.pm
installdirs:  site
requires:
    Config::General:               0
    File::Spec::Functions:         0
    IO::Prompt:                    0
    List::Compare:                 0
    Params::Validate:              0
    Spiffy:                        0.24
    Test::More:                    0
    WWW::Mechanize:                1.2
    YAML:                          0.39

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
