# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Sitebase
version:      0.4
version_from: lib/WWW/Sitebase.pm
installdirs:  site
requires:
    File::Spec::Functions:         0
    IO::Prompt:                    0
    List::Compare:                 0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
